### ISSUE TITLE
Handle nreads="variable"

### ISSUE THREAD

**Issue by bruvellu** [nelas/sra.py#1]
Just stumbled upon this [record](http://www.ncbi.nlm.nih.gov/sra/?term=876163). It broke my regex...

**Comment by victorfica** [comment]
Hi nelas , im new on github. I was working on something very very similar to this project, so I was testing your code and i found the same problem. I worked out catching the exception and assigning it nread = 0. Since im not really good with regex was my first option. So if nreads is variable, this value will be 0.
```
try:
     self.nreads = int(fields['nreads'])
except:
     self.nreads = 0
```

**Comment by bruvellu** [comment]
Hi @victorfica, that's a good suggestion! Thanks. Have you bumped into any record that the number of reads is actually variable? The example I found is simply a single-end, from what I can tell.

I'm just deciding whether it's worth to set the value to `0` or simply set it to `1`, since they should all be at least single-end :smile:
